-- AlterTable
ALTER TABLE "Mentorship" ALTER COLUMN "title" DROP DEFAULT,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "category" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Startup" ALTER COLUMN "category" DROP DEFAULT,
ALTER COLUMN "stage" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
